### ISSUE TITLE
The raw and compiled code snippets in notion seem to cut off after a few lines (around 30)

### ISSUE THREAD

**Issue by ksbystrom** [rfdearborn/dbt-docs-to-notion#23]
I have a large dbt project that I am writing to notion. It mostly works well, except the code snippets are all partially cut off. Is this a notion limitation?

**Comment by rfdearborn** [comment]
Yeah, unfortunately: https://github.com/rfdearborn/dbt-docs-to-notion/blob/6f49838f5dca6c4dec11ae8539d84dd8d1ad58c7/dbt_docs_to_notion.py#L395

(At least at the time of writing)
